version: '3.8'
services:
    mariadb:
        image: mariadb:10.5
        container_name: geocaching_mariadb
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/fixtures:/docker-entrypoint-initdb.d/
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=geocaching
            - MYSQL_USER=geocaching
            - MYSQL_PASSWORD=password

    webserver:
        image: nginx:alpine
        container_name: geocaching_webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8000:80'

    php-fpm:
        build: docker/php-fpm
        container_name: geocaching_php
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini

    phpmyadmin:
        depends_on:
            - mariadb
        image: phpmyadmin/phpmyadmin:latest
        container_name: geocaching_phpmyadmin
        logging:
            driver: none
        environment:
            - PMA_HOST=mariadb
            - PMA_USER=root
            - PMA_PASSWORD=password
        ports:
            - 8001:80
        volumes:
            - /sessions