name: Check on commit
on:
    push:
        branches-ignore:
            - master

jobs:
    analyze-php:
        name: Analyze PHP code
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache Composer Downloads
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Cache PHP dependencies
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

            - name: Install dependencies
              uses: php-actions/composer@v6
              with:
                  php_version: 8.3

            - name: Analyze PHP code
              run: composer phpstan

    # analyze-js:
    #     name: Analyze JS code
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: "Checkout"
    #           uses: actions/checkout@v3

    #         - name: Analyze JS code
    #           uses: actions/setup-node@v3
    #           with:
    #               node-version: 20
    #         - run: npm ci
    #         - run: npm run check
